apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling-multiple-up-mishil
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scaling-multiple-up-mishil
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scaling-multiple-up-mishil
      name: scaling-multiple-up-mishil
    spec:
      containers:
      - env:
        - name: RUN_TYPE
          value: cpu
        - name: CPU_PERCENT
          value: "85"
        image: beekman9527/cpumemload:latest
        imagePullPolicy: Always
        name: scaling-multiple-up-mishil-cpu-spec
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: RUN_TYPE
          value: memory
        - name: MEMORY_NUM
          value: "230"
        image: beekman9527/cpumemload:latest
        imagePullPolicy: Always
        name: scaling-multiple-up-mishil-mem-spec
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
