apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
ReclaimPolicy: Delete 
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  encrypted: "true"
