apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: t8c-client-operator
spec:
  channel: stable
  name: t8c-client-operator
  source: t8c-client-operator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
