apiVersion: v1
kind: Namespace
metadata:
  # turbo is default value used in the samples provided
  name: turbo-tsc
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: t8c-client-operator-catalog
  namespace: olm
spec:
  grpcPodConfig:
    securityContextConfig: restricted
  displayName: Turbonomic Client Operator
  image: icr.io/cpopen/t8c-client-operator-catalog
  publisher: Turbonomic.com
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 60m
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: turbonomic-operators
  namespace: turbo-tsc
spec:
  targetNamespaces:
  - turbo-tsc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: t8c-client-operator
  namespace: turbo-tsc
spec:
  channel: stable
  name: t8c-client-operator
  source: t8c-client-operator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
---
apiVersion: clients.turbonomic.ibm.com/v1alpha1
kind: TurbonomicClient
metadata:
  name: turbonomicclient-release
  namespace: turbo-tsc
spec:
  global:
    version: 8.13.2
---
apiVersion: clients.turbonomic.ibm.com/v1alpha1
kind: VersionManager
metadata:
  name: versionmanager-release
  namespace: turbo-tsc
spec:
  url: 'http://remote-nginx-tunnel:9080/cluster-manager/clusterConfiguration'
---
