apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
spec:
  # This configuration file is used for production.
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Default values for xl for use in Azure only with the storage class named: managed
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Any changes run : kubectl apply -f deploy/crds/charts_v1alpha1_xl_cr.yaml -n turbonomic

  # Global settings
  global:
    # registry: 
    # imageUsername: 
    # imagePassword: 
    repository: icr.io/cpopen/turbonomic
    tag: 8.17.1-SNAPSHOT
    telemetry:
      enabled: false
  # externalIP: 10.0.2.15
  # externalDbIP: 10.0.2.15
  # externalTimescaleDBIP: 10.0.2.15
  # enableExternalSecrets: true
    storageClassName: default
  # storageClassName: azurefile-csi
    deploymentMode: CLOUDABILITY_PREMIUM
    # deploymentModes available: HYBRID_SAAS, SERVER, SAAS_TRIAL, CLOUDABILITY_PREMIUM
  properties:
    extractor:
      grafanaAdminPassword: grafana
    topology-processor:
      resizeDownWarmUpIntervalHours: 0
    market: 
      suspensionThrottlingPerCluster: false
    api:
      frontdoorDisableOverride: true
    #global:
    #  featureFlags:
    #    enableMandatoryProbeAuth: false
    #    enableProbeAuth: true
      #oauth2:
      #  audience: turbonomic
  grafana:
    # Grafana is disabled by default. To enable it, uncomment:
    enabled: false
    adminPassword: grafana
    grafana.ini:
      database:
        # Store data in sqlite3 (no persistence across restarts) by default. To persist, uncomment:
        type: postgres
        password: grafana
  #TSC server components
  nginx:
    externalTrafficPolicy: Cluster
    tunnel:
      expose: true
  rsyslog:
    tunnel:
      expose: true
  tunnel:
    enabled: true
    mode: server
  client-network:
    enabled: true
  # Component selector - Probes
  actionscript:
    enabled: false
  #oauth2:
  #  enabled: true
  db:
    persistence:
      size: 100Gi
  server-power-modeler:
    enabled: false
  #suspend:
  #  enabled: false
  azure:
    enabled: true
  webhooks:
    enabled: true
  actionscripts:
    enabled: false
  # Embedded Reporting
  timescaledb:
    enabled: false
  postgresql:
    persistence:
      size: 110Gi
  extractor:
    enabled: false
  reporting:
    enabled: false
  cloudability:
    enabled: false
  apptio-sftp:
    enabled: true
