apiVersion: clients.turbonomic.ibm.com/v1alpha1
kind: VersionManager
metadata:
  name: versionmanager-release
  namespace: turbo-tsc
spec:
  url: 'http://remote-nginx-tunnel:9080/cluster-manager/clusterConfiguration'
